# Generated by Django 4.2.1 on 2023-06-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
