# Generated by Django 4.2.1 on 2023-07-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='folder_name',
        ),
    ]
