# Generated by Django 4.2.1 on 2023-07-02 23:03

from django.db import migrations, models
import lots.models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_remove_imageupload_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='folder_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=lots.models.image_upload_path),
        ),
    ]
