# Generated by Django 4.2.1 on 2023-07-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_imageupload_folder_name_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
